[colors]
background = '#2F3857'
foreground = '#439fb6'

# need change>
cursor_bg = '#c6c8d1'
cursor_border = '#c6c8d1'
cursor_fg = '#161821'
selection_bg = '#c6c8d1'
selection_fg = '#161821'
# <need change

ansi = [
  '#323145', # black
  '#e27878', # maroon*
  '#439fb6', # green
  '#e2a478', # olive*
  '#84a0c6', # navy*
  '#a093c7', # purple*
  '#89b8c2', # teal
  '#c6c8d1', # silver
]

brights = [
  '#6b7089', # grey*
  '#bf1725', # red
  '#c0ca8e', # lime*
  '#E8E8A1', # yellow
  '#91acd1', # blue*
  '#ada0d3', # fuchsia*
  '#95c4ce', # aqua*
  '#dce7e9', # white
]

[colors.indexed]

[metadata]
name = 'lain'
